# Generated by Django 3.2.13 on 2022-06-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0002_auto_20220618_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripwaypointdata',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
