# Generated by Django 3.2.13 on 2022-06-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0003_tripwaypointdata_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='name',
            field=models.CharField(blank=True, default='place_name', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
