# Generated by Django 3.2.13 on 2022-06-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0004_auto_20220618_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True),
        ),
    ]
