# Generated by Django 3.2.13 on 2022-07-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0005_auto_20220618_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
